### ISSUE TITLE
SCSS Compilation - Missing Readme Section

### ISSUE THREAD

**Issue by app-generator** [app-generator/sample-django-best-practices#3]
Hello @koladev32,

Please update the README with a new section that informs the user how to compile SCSS and regenerate the CSS Files

Ty!

**Comment by koladev32** [comment]
Hey @app-generator, 

Actually, no need to compile the files manually, it's automatically handled. Maybe we can add a section explaining it? 
what do you think?

**Comment by app-generator** [comment]
perfect

**Comment by koladev32** [comment]
Good here!

**Comment by app-generator** [comment]
Closing! Ty @koladev32
