### ISSUE TITLE
Docker Exec - Fails for missing `.env`

### ISSUE THREAD

**Issue by app-generator** [app-generator/sample-django-best-practices#4]
Hello @koladev32

The Docker execution exits with error `.env: The system cannot find the file specified.`

Please add `.env.sample` with default values and associate comments to inform the user about it. 

Also, README should be updated to mention the `.env` creation from `.env.sample`

Ty!

**Comment by koladev32** [comment]
Good here!

**Comment by app-generator** [comment]
The issue persists in the latest version:

```log
$ cd sample-django-best-practices
$ git pull
Already up to date.
$ docker container kill $(docker ps -q) ; docker container rm $(docker ps -a -q) ; docker network prune -f ; docker-compose up --build
open D:\work\repo-samples\sample-django-best-practices\.env: The system cannot find the file specified.
```

**Comment by app-generator** [comment]
Closing!
