### ISSUE TITLE
Docker ports Update

### ISSUE THREAD

**Issue by app-generator** [app-generator/sample-django-best-practices#5]
Hello @koladev32 

Please configure Docker to use the below ports: 

- 5005 for the Gunicorn (not exposed)
- 85 for the Nginx (exposed) 

As for all other AppSeed kits, once the user type `docker-compose up --build` the app should be LIVE at: 

`http://localhost:85` 

P.S. Usually ports 5000, and 80 are taken by other services. 

ty!

**Comment by koladev32** [comment]
Good here!

**Comment by app-generator** [comment]
The app serves `5005` and `85` is not usable. 
The Docker set up should keep private the port 5005 `gunicorn` and expose only the port 85 (Nginx). 

P.S. Tested in latest revision.

**Comment by app-generator** [comment]
Closing
