### ISSUE TITLE
Unitary Tests - No tests are executed

### ISSUE THREAD

**Issue by app-generator** [app-generator/sample-django-best-practices#7]
Hello @koladev32 

Please add a minimal test suite for the existing features:

- register ok
- login ok
- registration with existing email 
- registration using a week password 
- login using an unexisting user
- login using the wrong password. 

All test data should be deleted at the end of the test suite. 

P.S. The tests section should be also mentioned on the README. 

Ty!

**Comment by koladev32** [comment]
Hey @app-generator 

For these tests, I am thinking about testing the forms to make sure these functionalities are working. 

What do you think?

**Comment by app-generator** [comment]
Hello @koladev32 

The goal is to cover the use case and maximize the code coverage. 
Please proceed with your proposal.

Ty!

**Comment by koladev32** [comment]
Hey @app-generator 

Added some test cases here

**Comment by app-generator** [comment]
Tested with the latest version - No tests are executed: 

```log
(env) PS D:\work\repo-samples\sample-django-best-practices> git pull
Already up to date.
(env) PS D:\work\repo-samples\sample-django-best-practices> 
(env) PS D:\work\repo-samples\sample-django-best-practices>
(env) PS D:\work\repo-samples\sample-django-best-practices>
(env) PS D:\work\repo-samples\sample-django-best-practices> python manage.py test
System check identified no issues (0 silenced).

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
(env) PS D:\work\repo-samples\sample-django-best-practices> 
```

**Comment by app-generator** [comment]
@koladev32 - any progress here? 
ty!

**Comment by koladev32** [comment]
Ah yes. Actually, `pytest` was used to write the tests. So you need to use the `pytest` command instead. Might add it to the README.md.

**Comment by app-generator** [comment]
Cool, please update the README with a small section that mentions the command + executed test suite

**Comment by app-generator** [comment]
ty for your work @koladev32
