### ISSUE TITLE
Docker Set Up - Assets not loaded

### ISSUE THREAD

**Issue by app-generator** [app-generator/sample-django-best-practices#8]
![image](https://user-images.githubusercontent.com/51070104/169684359-b1e15833-0b86-4838-a03d-a2aec8e546a9.png)

**Comment by app-generator** [comment]
hello @koladev32 
any progress on this? ty

**Comment by koladev32** [comment]
Hi @app-generator 

I pushed a fix. Sorry I haven't noticed here. Please let me know how it goes

**Comment by app-generator** [comment]
Working. Ty for the fix @koladev32 
Closing!
